planner_configs:
  RRTConnect: {type: geometric::RRTConnect, range: 0.2}
  RRTstar: {type: geometric::RRTstar}

manipulator:
  default_planner_config: RRTConnect
  planner_configs:
    - RRTConnect
    - RRTstar
